{"nick":"jenkins-monitor","reason":"Remote host closed the connection","date":"2016-12-16T00:05:05.850Z","type":"quit"}
{"nick":"jenkins-monitor","date":"2016-12-16T00:05:13.832Z","type":"join"}
{"nick":"jenkins-monitor","reason":"Remote host closed the connection","date":"2016-12-16T00:10:03.240Z","type":"quit"}
{"nick":"jenkins-monitor","date":"2016-12-16T00:10:10.473Z","type":"join"}
{"nick":"jenkins-monitor","reason":"Remote host closed the connection","date":"2016-12-16T00:15:04.273Z","type":"quit"}
{"nick":"jenkins-monitor","date":"2016-12-16T00:15:11.622Z","type":"join"}
{"nick":"imyller","reason":"Quit: My iMac has gone to sleep. ZZZzzzâ€¦","date":"2016-12-16T00:55:51.405Z","type":"quit"}
{"nick":"Trott","message":"The test widget seems to be reporting failures on test/arm whether the job fails or succeeds. Most recent example I've come across is https://github.com/nodejs/node/pull/10291 but it's definitely not the only one I've seen today.  /cc jbergstroem","date":"2016-12-16T05:24:28.605Z","type":"message"}
{"nick":"jbergstroem","message":"ouch","date":"2016-12-16T05:25:06.155Z","type":"message"}
{"nick":"jbergstroem","message":"see i shall","date":"2016-12-16T05:25:15.750Z","type":"message"}
{"nick":"jbergstroem","message":"perhaps when at waking hour","date":"2016-12-16T05:25:30.044Z","type":"message"}
{"nick":"imyller","date":"2016-12-16T07:33:03.004Z","type":"join"}
