{"nick":"jerrysv","date":"2016-06-19T00:00:15.066Z","type":"join"}
{"nick":"rgrinberg","date":"2016-06-19T00:59:06.606Z","type":"join"}
{"nick":"bret","reason":"Quit: Updating details, brb","date":"2016-06-19T01:24:16.501Z","type":"quit"}
{"nick":"bret","date":"2016-06-19T01:24:57.360Z","type":"join"}
{"nick":"Xinayder","reason":"Ping timeout: 244 seconds","date":"2016-06-19T03:14:52.099Z","type":"quit"}
{"nick":"Xinayder","date":"2016-06-19T03:22:03.547Z","type":"join"}
{"nick":"rgrinberg","reason":"Ping timeout: 260 seconds","date":"2016-06-19T03:40:50.447Z","type":"quit"}
{"nick":"jerrysv","reason":"Remote host closed the connection","date":"2016-06-19T04:22:14.525Z","type":"quit"}
{"nick":"rgrinberg","date":"2016-06-19T14:54:33.166Z","type":"join"}
{"nick":"jerrysv","date":"2016-06-19T16:54:19.714Z","type":"join"}
{"nick":"jerrysv","reason":"Remote host closed the connection","date":"2016-06-19T18:33:21.380Z","type":"quit"}
{"nick":"rook2paw1","new_nick":"rook2pawn","date":"2016-06-19T18:43:03.790Z","type":"nick"}
{"nick":"ralphthe1inja","date":"2016-06-19T18:45:07.968Z","type":"join"}
{"nick":"ralphtheninja","reason":"*.net *.split","date":"2016-06-19T18:50:08.678Z","type":"quit"}
{"nick":"daleharvey","date":"2016-06-19T19:30:40.003Z","type":"join"}
{"nick":"daleharvey","message":"Hey, so what is expected behaviour when you call .get etc after a .close / .destroy ?","date":"2016-06-19T19:31:45.616Z","type":"message"}
{"nick":"daleharvey","message":"right now our code seems to be hanging, not sure if its leveldowns fault or possibly sublevel","date":"2016-06-19T19:32:19.103Z","type":"message"}
{"nick":"substack","message":"> var db = require('level')('/tmp/xyz'); db.close(function () { db.get('whatever', function (err) { console.log(err) }) })","date":"2016-06-19T19:40:33.353Z","type":"message"}
{"nick":"substack","message":"[ReadError: Database is not open]","date":"2016-06-19T19:40:41.068Z","type":"message"}
{"nick":"substack","message":"and that seems like what I would expect to happen","date":"2016-06-19T19:40:58.398Z","type":"message"}
{"nick":"substack","message":"win 37","date":"2016-06-19T19:41:10.711Z","type":"message"}
{"nick":"daleharvey","message":"yeh same, cheers","date":"2016-06-19T19:46:55.824Z","type":"message"}
{"nick":"daleharvey","message":"> var leveldown = require('leveldown'); var db = leveldown('/tmp/abc'); db.close(function () { db.get('whatever', function (err) { console.log(err) }) })","date":"2016-06-19T19:47:03.083Z","type":"message"}
{"nick":"daleharvey","message":"am I doing something wrong there? that gives me > Segmentation fault: 11","date":"2016-06-19T19:47:22.390Z","type":"message"}
{"nick":"substack","message":"I think that error is caused by leveldown not being open yet","date":"2016-06-19T19:49:07.337Z","type":"message"}
{"nick":"substack","message":"if you put the rest of that inside leveldown.open(function () {}) it might work","date":"2016-06-19T19:49:23.189Z","type":"message"}
{"nick":"substack","message":"level{up,} batches operations until the handle is open, so you don't get those errors","date":"2016-06-19T19:49:52.380Z","type":"message"}
{"nick":"substack","message":"still crashes for me using .open(), weird","date":"2016-06-19T19:51:32.712Z","type":"message"}
{"nick":"daleharvey","message":"hrm, we arent getting a crash either way in our use case, so probably the wrong rabbit hole for me at least","date":"2016-06-19T19:59:50.229Z","type":"message"}
{"nick":"daleharvey","message":"our problem is users doing something like db.query(); db.destroy(); basically at any point of our code cant depend on having an open db, right now level calls are getting hangs, need to figure out where is hiding it","date":"2016-06-19T20:01:55.842Z","type":"message"}
{"nick":"ralphthe1inja","new_nick":"ralphtheninja","date":"2016-06-19T20:14:27.042Z","type":"nick"}
{"nick":"jerrysv","date":"2016-06-19T22:28:05.155Z","type":"join"}
{"nick":"jerrysv","reason":"Remote host closed the connection","date":"2016-06-19T22:37:01.673Z","type":"quit"}
