{"nick":"jmar777","date":"2013-08-23T01:13:36.063Z","type":"join"}
{"nick":"lummox","reason":"Ping timeout: 256 seconds","date":"2013-08-23T01:25:25.497Z","type":"quit"}
{"nick":"lummox","date":"2013-08-23T01:26:20.538Z","type":"join"}
{"nick":"abraxas","date":"2013-08-23T01:28:25.376Z","type":"join"}
{"nick":"jmar777","reason":"Remote host closed the connection","date":"2013-08-23T01:32:46.015Z","type":"quit"}
{"nick":"c4milo","date":"2013-08-23T02:12:56.381Z","type":"join"}
{"nick":"c4milo","reason":"Remote host closed the connection","date":"2013-08-23T04:16:16.193Z","type":"quit"}
{"nick":"spolu","date":"2013-08-23T06:39:52.929Z","type":"join"}
{"nick":"Lethalman","date":"2013-08-23T07:07:53.747Z","type":"join"}
{"nick":"C-Man","date":"2013-08-23T08:04:11.637Z","type":"join"}
{"nick":"bnoordhuis","date":"2013-08-23T08:50:50.001Z","type":"join"}
{"nick":"spolu","reason":"Ping timeout: 248 seconds","date":"2013-08-23T08:53:57.710Z","type":"quit"}
{"nick":"Net147","date":"2013-08-23T09:09:52.383Z","type":"join"}
{"nick":"juanjosanchez","date":"2013-08-23T09:43:02.165Z","type":"join"}
{"nick":"aboudreault","message":"emm.. when writing internal function (not exposed, but used by exposed functions), do you usually throwexception and rethrow it in the Javascript function?","date":"2013-08-23T10:48:57.127Z","type":"message"}
{"nick":"aboudreault","message":"trying to make my code cleaner as I can between the JS function and internal ones","date":"2013-08-23T10:49:16.411Z","type":"message"}
{"nick":"bnoordhuis","message":"aboudreault: in node.js, we usually return an error code from c++ land, then have the js wrapper turn that into an exception","date":"2013-08-23T10:52:01.055Z","type":"message"}
{"nick":"bnoordhuis","message":"makes for slightly nicer stack traces","date":"2013-08-23T10:52:08.258Z","type":"message"}
{"nick":"aboudreault","message":"funny, I was currently trying to find a good example of this in node js code.","date":"2013-08-23T10:52:41.239Z","type":"message"}
{"nick":"bnoordhuis","message":"aboudreault: grep for args.GetReturnValue().Set(err)","date":"2013-08-23T10:53:42.639Z","type":"message"}
{"nick":"aboudreault","message":"bnoordhuis, seems a good idea. any file to point me I could look?","date":"2013-08-23T10:53:44.034Z","type":"message"}
{"nick":"bnoordhuis","message":"see above :)","date":"2013-08-23T10:53:49.649Z","type":"message"}
{"nick":"aboudreault","message":"thanks :)","date":"2013-08-23T10:53:55.279Z","type":"message"}
{"nick":"bnoordhuis","message":"make sure you're on master though, the v0.10 code base is quite different","date":"2013-08-23T10:54:02.630Z","type":"message"}
{"nick":"aboudreault","message":"alright","date":"2013-08-23T10:54:11.083Z","type":"message"}
{"nick":"spolu","date":"2013-08-23T11:05:49.267Z","type":"join"}
{"nick":"stampho","reason":"Remote host closed the connection","date":"2013-08-23T11:23:51.777Z","type":"quit"}
{"nick":"abraxas","reason":"Remote host closed the connection","date":"2013-08-23T11:24:20.344Z","type":"quit"}
{"nick":"carif","reason":"Quit: Ex-Chat","date":"2013-08-23T12:51:53.809Z","type":"quit"}
{"nick":"jmar777","date":"2013-08-23T12:56:56.461Z","type":"join"}
{"nick":"c4milo","date":"2013-08-23T13:56:59.369Z","type":"join"}
{"nick":"Net147","reason":"Quit:  HydraIRC -> http://www.hydrairc.com <-","date":"2013-08-23T14:21:36.602Z","type":"quit"}
{"nick":"c4milo","reason":"Remote host closed the connection","date":"2013-08-23T14:30:34.921Z","type":"quit"}
{"nick":"c4milo","date":"2013-08-23T14:38:24.916Z","type":"join"}
{"nick":"spolu","reason":"Ping timeout: 246 seconds","date":"2013-08-23T14:41:34.951Z","type":"quit"}
