{"nick":"bnoordhuis","date":"2013-09-08T00:05:24.282Z","type":"join"}
{"nick":"bnoordhuis","reason":"Ping timeout: 268 seconds","date":"2013-09-08T00:10:34.078Z","type":"quit"}
{"nick":"jmar777","date":"2013-09-08T05:10:49.613Z","type":"join"}
{"nick":"Lethalman","date":"2013-09-08T07:06:37.346Z","type":"join"}
{"nick":"jmar777","reason":"Remote host closed the connection","date":"2013-09-08T07:21:35.339Z","type":"quit"}
{"nick":"C-Man","date":"2013-09-08T07:57:30.019Z","type":"join"}
{"nick":"bnoordhuis","date":"2013-09-08T09:11:22.609Z","type":"join"}
{"nick":"seventh","reason":"Ping timeout: 245 seconds","date":"2013-09-08T09:30:50.126Z","type":"quit"}
{"nick":"carif","date":"2013-09-08T09:39:52.670Z","type":"join"}
{"nick":"carif","reason":"Ping timeout: 264 seconds","date":"2013-09-08T09:44:16.481Z","type":"quit"}
{"nick":"hio","date":"2013-09-08T12:48:38.225Z","type":"join"}
{"nick":"hio","message":"how does v8 stop execution when a breakpoint hits? software interrupt or something?","date":"2013-09-08T12:49:09.929Z","type":"message"}
{"nick":"Lethalman","reason":"Read error: Connection reset by peer","date":"2013-09-08T13:03:50.269Z","type":"quit"}
{"nick":"bnoordhuis","message":"hio: js functions have a 'is interrupt pending' check in the prolog","date":"2013-09-08T13:06:06.555Z","type":"message"}
{"nick":"bnoordhuis","message":"where 'interrupt' is a thread-local flag","date":"2013-09-08T13:06:39.559Z","type":"message"}
{"nick":"hio","message":"bnoordhuis, so do I understand you correctly: The c++ code gets executed, it throws an interrupt (however it achieves doing so), and then halts program execution, making it possible to use debug api calls?","date":"2013-09-08T13:17:51.821Z","type":"message"}
{"nick":"hio","message":"also what is a \"prolog\"?","date":"2013-09-08T13:18:05.406Z","type":"message"}
{"nick":"bnoordhuis","message":"hio: it's probably easiest to demonstrate it","date":"2013-09-08T13:20:49.797Z","type":"message"}
{"nick":"hio","message":"bnoordhuis, so do I understand you correctly: The c++ code gets executed, it throws an interrupt (however it achieves doing so), and then halts program execution, making it possible to use debug api calls?","date":"2013-09-08T13:21:02.374Z","type":"message"}
{"nick":"hio","message":"sorry, misclicked","date":"2013-09-08T13:21:07.202Z","type":"message"}
{"nick":"bnoordhuis","message":"compile a debug build, run d8 with --expose_debug_as=D, then run D.Debug.disassemble(function(){})","date":"2013-09-08T13:21:13.305Z","type":"message"}
{"nick":"hio","message":"ok I will ","date":"2013-09-08T13:21:24.898Z","type":"message"}
{"nick":"bnoordhuis","message":"you'll see a call to InterruptStub in there at the start of the function","date":"2013-09-08T13:21:25.232Z","type":"message"}
{"nick":"hio","message":"thank you for your help, I appreciate it","date":"2013-09-08T13:21:35.806Z","type":"message"}
{"nick":"bnoordhuis","message":"no problem :)","date":"2013-09-08T13:21:40.781Z","type":"message"}
{"nick":"Jarvix__","date":"2013-09-08T13:23:04.031Z","type":"join"}
{"nick":"Jarvix_","reason":"Ping timeout: 264 seconds","date":"2013-09-08T13:26:30.385Z","type":"quit"}
{"nick":"wfh","reason":"Ping timeout: 264 seconds","date":"2013-09-08T13:27:06.285Z","type":"quit"}
{"nick":"wfh","date":"2013-09-08T13:27:26.114Z","type":"join"}
{"nick":"hio","message":"I see a call to InterruptCheck, not \"InterruptStub\" though","date":"2013-09-08T13:30:47.624Z","type":"message"}
{"nick":"bnoordhuis","reason":"Ping timeout: 264 seconds","date":"2013-09-08T13:38:52.371Z","type":"quit"}
{"nick":"hio","message":"when I embed v8, is it running in the same process as my host application or is it going to start a new process anyway?","date":"2013-09-08T14:28:09.094Z","type":"message"}
{"nick":"jmar777","date":"2013-09-08T14:31:08.685Z","type":"join"}
{"nick":"bnoordhuis","date":"2013-09-08T14:33:14.227Z","type":"join"}
{"nick":"bnoordhuis","message":"hio: that changed in recent v8 releases iirc","date":"2013-09-08T14:43:05.305Z","type":"message"}
{"nick":"jmar777","reason":"Remote host closed the connection","date":"2013-09-08T15:02:04.382Z","type":"quit"}
{"nick":"jmar777","date":"2013-09-08T15:12:49.400Z","type":"join"}
{"nick":"jmar777","reason":"Remote host closed the connection","date":"2013-09-08T15:17:44.145Z","type":"quit"}
{"nick":"RT|Chatzilla","reason":"Quit: ChatZilla 0.9.86.1 [Firefox 2.0.0.22pre/2009081014]","date":"2013-09-08T15:24:29.362Z","type":"quit"}
{"nick":"seventh","date":"2013-09-08T15:46:46.974Z","type":"join"}
{"nick":"Lethalman","date":"2013-09-08T16:37:53.170Z","type":"join"}
{"nick":"bnoordhuis","reason":"Ping timeout: 267 seconds","date":"2013-09-08T16:40:04.494Z","type":"quit"}
{"nick":"bnoordhuis","date":"2013-09-08T16:58:38.642Z","type":"join"}
{"nick":"iamdustan","reason":"Ping timeout: 240 seconds","date":"2013-09-08T17:20:38.537Z","type":"quit"}
{"nick":"hio","date":"2013-09-08T18:40:44.963Z","type":"part"}
{"nick":"c4milo","date":"2013-09-08T18:45:36.755Z","type":"join"}
{"nick":"c4milo","reason":"Remote host closed the connection","date":"2013-09-08T18:50:26.864Z","type":"quit"}
{"nick":"c4milo","date":"2013-09-08T19:33:47.059Z","type":"join"}
