{"nick":"plutoniix","date":"2017-06-16T00:18:51.062Z","type":"join"}
{"nick":"unixpickle","date":"2017-06-16T00:33:21.606Z","type":"join"}
{"nick":"unixpickle","reason":"Quit: My Mac has gone to sleep. ZZZzzzâ€¦","date":"2017-06-16T01:51:40.199Z","type":"quit"}
{"nick":"bradleymeck","reason":"Quit: bradleymeck","date":"2017-06-16T03:08:13.259Z","type":"quit"}
{"nick":"mylesborins","reason":"Quit: farewell for now","date":"2017-06-16T10:25:11.337Z","type":"quit"}
{"nick":"mylesborins","date":"2017-06-16T10:25:41.921Z","type":"join"}
{"nick":"Garbee","date":"2017-06-16T10:47:01.768Z","type":"join"}
{"nick":"plutoniix","reason":"Quit: Leaving","date":"2017-06-16T12:50:18.097Z","type":"quit"}
{"nick":"bradleymeck","date":"2017-06-16T13:06:46.464Z","type":"join"}
{"nick":"littledan","message":"I'm trying to reproduce https://bugs.chromium.org/p/chromium/issues/detail?id=716468#c3 locally. However, I'm running into some authentication issues with getting the telemetry test: AccessDeniedException: 403 Caller does not have storage.objects.list access to bucket chrome-partner-telemetry. Has anyone else run into this issue?","date":"2017-06-16T13:21:14.292Z","type":"message"}
{"nick":"littledan","message":"am I supposed to have access?","date":"2017-06-16T13:21:30.725Z","type":"message"}
{"nick":"RT|Chatzilla","reason":"Read error: Connection reset by peer","date":"2017-06-16T13:22:34.644Z","type":"quit"}
{"nick":"RT|Chatzilla","date":"2017-06-16T13:26:20.287Z","type":"join"}
{"nick":"littledan","message":"is there some way I could be come a whitelisted Google partner (as listed here: http://www.chromium.org/developers/telemetry/upload_to_cloud_storage) so I can debug my patch?","date":"2017-06-16T13:28:48.232Z","type":"message"}
{"nick":"bradleymeck","message":"how \"experimental\" is Private these days?","date":"2017-06-16T13:29:02.746Z","type":"message"}
{"nick":"RT|Chatzilla","reason":"Quit: ChatZilla 0.9.86.1 [Firefox 2.0.0.22pre/2010030309]","date":"2017-06-16T13:35:22.803Z","type":"quit"}
{"nick":"RT|Chatzilla","date":"2017-06-16T13:40:20.704Z","type":"join"}
{"nick":"unixpickle","date":"2017-06-16T13:45:08.180Z","type":"join"}
{"nick":"bradleymeck","message":"also, trying to figure out what `entry_stack_ != __null` Check failing means when using snapshot creator. I feel like I have properly disposed of the snapshotcreator, called snapshot_isolate->Exit(); and node_isolate->Enter(); ...","date":"2017-06-16T13:54:58.030Z","type":"message"}
{"nick":"bradleymeck","message":"oh, it looks like I need to manually delete (more than dispose?) the snapshot isolate??","date":"2017-06-16T14:14:47.662Z","type":"message"}
{"nick":"bradleymeck","message":"oh nm","date":"2017-06-16T14:17:38.898Z","type":"message"}
{"nick":"bradleymeck","message":"nope nope, still a problem","date":"2017-06-16T14:26:06.834Z","type":"message"}
{"nick":"bradleymeck","reason":"Quit: bradleymeck","date":"2017-06-16T15:38:36.612Z","type":"quit"}
{"nick":"bradleymeck","date":"2017-06-16T15:46:19.517Z","type":"join"}
{"nick":"bradleymeck","reason":"Quit: bradleymeck","date":"2017-06-16T15:51:36.632Z","type":"quit"}
