{"nick":"ircretary","reason":"Remote host closed the connection","date":"2013-08-18T00:00:00.741Z","type":"quit"}
{"nick":"ircretary","date":"2013-08-18T00:00:08.343Z","type":"join"}
{"nick":"indexzero","date":"2013-08-18T00:30:09.294Z","type":"join"}
{"nick":"toddaaro","date":"2013-08-18T00:48:29.854Z","type":"join"}
{"nick":"acrichto","date":"2013-08-18T00:48:31.009Z","type":"join"}
{"nick":"Domenic_","message":"what's the python test runner command again? that'll do glob tests and such?","date":"2013-08-18T00:50:21.758Z","type":"message"}
{"nick":"acrichto","message":"I was playing around with libuv recently adding some bindings for process management to rust, but I was having some problems. I ended up getting it whittled down to https://gist.github.com/alexcrichton/6259377. In that code I would expect the statement in 'on_exit' to be printed twice, but that doesn't always happen. Am I using libuv in a wrong way somehow? The most recent version I've tried this on is 0.10.13","date":"2013-08-18T00:50:33.005Z","type":"message"}
{"nick":"indexzero","reason":"Quit: indexzero","date":"2013-08-18T00:51:03.173Z","type":"quit"}
{"nick":"mmalecki","new_nick":"mmalecki[zzz]","date":"2013-08-18T00:54:24.856Z","type":"nick"}
{"nick":"isaacs","message":"Domenic_: python tools/test.py simple/test-http*","date":"2013-08-18T00:54:48.244Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: ty. in the home stretch here.","date":"2013-08-18T00:54:59.522Z","type":"message"}
{"nick":"AvianFlu","reason":"Remote host closed the connection","date":"2013-08-18T00:55:11.319Z","type":"quit"}
{"nick":"isaacs","message":"Domenic_: nice :)","date":"2013-08-18T00:55:13.518Z","type":"message"}
{"nick":"Domenic_","message":"how do i read the messages test output?","date":"2013-08-18T00:58:45.451Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: message test failures means that the output of test/messages/*.js didn't match test/messages/*.out","date":"2013-08-18T01:04:26.975Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: got that part. but, what does the output mean when it fails? it just spews a bunch of stuff at me.","date":"2013-08-18T01:04:49.290Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: the output is kinda weird, but it tries to point out 1) if the number of lines differs, and 2) the first line where they differ","date":"2013-08-18T01:04:51.336Z","type":"message"}
{"nick":"isaacs","message":"yeah, it spews a bunch of stuff","date":"2013-08-18T01:04:58.267Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: i usually just diff the output withthe file when i see a failure","date":"2013-08-18T01:05:09.547Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: alias gdiff='git diff --no-index --color'","date":"2013-08-18T01:05:23.886Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: ok cool, thanks!","date":"2013-08-18T01:05:39.680Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: er, wrong one, hold on...","date":"2013-08-18T01:06:38.756Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: oh, wait, i don't have a hadny thing for running just one of those.","date":"2013-08-18T01:10:41.519Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: because they have globs, that's right.  and so i gave up.","date":"2013-08-18T01:10:49.945Z","type":"message"}
{"nick":"c4milo","date":"2013-08-18T01:11:45.098Z","type":"join"}
{"nick":"isaacs","message":"TooTallNate: probably just need to make Agent.prototype.request(options) sniff for a socket, and if it's got one, just make a ClientRequest and slap that socket on it","date":"2013-08-18T01:12:35.231Z","type":"message"}
{"nick":"TooTallNate","message":"isaacs: it should probably bypass Agent completely IMO","date":"2013-08-18T01:13:14.651Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: dammit. trying to express vm.js's statics in terms of smaller primitives screws up stack traces, introducing lines in vm.js into them.","date":"2013-08-18T01:17:18.782Z","type":"message"}
{"nick":"TooTallNate","message":"isaacs: no way... i'm compiling now to test... but i think it only takes +4 LOC","date":"2013-08-18T01:17:51.685Z","type":"message"}
{"nick":"TooTallNate","message":"lol","date":"2013-08-18T01:17:53.172Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: that's fine.  just update the tests","date":"2013-08-18T01:17:58.458Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: no, i think it's a much worse UX, so I should fix it.","date":"2013-08-18T01:18:11.103Z","type":"message"}
{"nick":"isaacs","message":"TooTallNate: well, http.get() ===> http.globalAgent.get()","date":"2013-08-18T01:18:19.437Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: it's fine to have a few extra lines at the bottom of the stack trace","date":"2013-08-18T01:18:34.312Z","type":"message"}
{"nick":"isaacs","message":"most people don't read more than a few down anyway","date":"2013-08-18T01:18:49.263Z","type":"message"}
{"nick":"isaacs","message":"you only care about the point in the stack where i'ts YOUR code","date":"2013-08-18T01:18:56.379Z","type":"message"}
{"nick":"Domenic_","message":"isaacs: no it screws up (a) the top of the stack trace; (b) the line of code displayed as causing the error","date":"2013-08-18T01:19:09.735Z","type":"message"}
{"nick":"isaacs","message":"context._mumboJumbo(..) (vm.js:123) is just extra","date":"2013-08-18T01:19:15.270Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: oh.. yes.  that's relevant, then","date":"2013-08-18T01:19:24.290Z","type":"message"}
{"nick":"isaacs","message":"no try/catch monkey business","date":"2013-08-18T01:19:34.502Z","type":"message"}
{"nick":"TooTallNate","message":"isaacs: hmm... is _http_client.js basically just all legacy code?","date":"2013-08-18T01:19:34.727Z","type":"message"}
{"nick":"isaacs","message":"doemrethrow","date":"2013-08-18T01:19:38.734Z","type":"message"}
{"nick":"isaacs","message":"Domenic_: rethrow <-- that ruins everything","date":"2013-08-18T01:19:47.529Z","type":"message"}
{"nick":"isaacs","message":"TooTallNate: no, _http_client is the ClientRequest class","date":"2013-08-18T01:19:59.926Z","type":"message"}
{"nick":"TooTallNate","message":"ya i see now","date":"2013-08-18T01:20:07.335Z","type":"message"}
{"nick":"isaacs","message":"TooTallNate: https://gist.github.com/isaacs/6259465","date":"2013-08-18T01:20:32.118Z","type":"message"}
{"nick":"isaacs","message":"TooTallNate: untested","date":"2013-08-18T01:20:35.382Z","type":"message"}
{"nick":"isaacs","message":"herp, didn't do else if","date":"2013-08-18T01:20:46.159Z","type":"message"}
{"nick":"TooTallNate","message":"isaacs: i mean ya that's basically what i got :p","date":"2013-08-18T01:21:01.550Z","type":"message"}
{"nick":"isaacs","message":"updated https://gist.github.com/isaacs/6259465","date":"2013-08-18T01:21:07.367Z","type":"message"}
{"nick":"isaacs","message":"TooTallNate: test is tedious, though :)","date":"2013-08-18T01:21:14.989Z","type":"message"}
{"nick":"TooTallNate","reason":"Quit: Computer has gone to sleep.","date":"2013-08-18T01:23:52.671Z","type":"quit"}
{"nick":"qard","date":"2013-08-18T01:37:33.338Z","type":"join"}
{"nick":"qard","reason":"Client Quit","date":"2013-08-18T01:37:38.182Z","type":"quit"}
{"nick":"acrichto","date":"2013-08-18T01:58:32.256Z","type":"part"}
{"nick":"tjfontaine","message":"yawn","date":"2013-08-18T02:01:11.126Z","type":"message"}
{"nick":"kazupon","date":"2013-08-18T02:06:24.899Z","type":"join"}
{"nick":"Domenic_","message":"what's the deal with \"util.debug: use console.error instead\"","date":"2013-08-18T02:16:23.010Z","type":"message"}
{"nick":"tjfontaine","message":"it's an old thing, do you actually want util.debuglog?","date":"2013-08-18T02:16:54.358Z","type":"message"}
{"nick":"Domenic_","message":"no idea, i'm just running some old tests and that happens","date":"2013-08-18T02:17:36.670Z","type":"message"}
{"nick":"tjfontaine","message":"they probably haven't been updated yet","date":"2013-08-18T02:17:51.314Z","type":"message"}
{"nick":"Domenic_","message":"so switching them to util.debuglog is the way to go?","date":"2013-08-18T02:18:02.821Z","type":"message"}
{"nick":"Domenic_","message":"i think it happens when doing common.debug","date":"2013-08-18T02:18:34.174Z","type":"message"}
{"nick":"tjfontaine","message":"if they're in test/* they should probably be console.err","date":"2013-08-18T02:18:36.727Z","type":"message"}
{"nick":"tjfontaine","message":"*error","date":"2013-08-18T02:18:39.726Z","type":"message"}
{"nick":"tjfontaine","message":"debuglog is mostly for lib/*","date":"2013-08-18T02:18:47.014Z","type":"message"}
{"nick":"Domenic_","message":"hmm ok","date":"2013-08-18T02:18:52.771Z","type":"message"}
{"nick":"Domenic_","message":"oh god i broke everything -_-","date":"2013-08-18T02:19:39.418Z","type":"message"}
{"nick":"Domenic_","message":"halp interpreting https://gist.github.com/domenic/6259629 stack trace","date":"2013-08-18T02:33:48.133Z","type":"message"}
{"nick":"tjfontaine","message":"oh the windows","date":"2013-08-18T02:35:19.604Z","type":"message"}
{"nick":"Domenic_","message":"i brought home my mac laptop if you think it'll be easier there?","date":"2013-08-18T02:37:34.186Z","type":"message"}
{"nick":"Domenic_","message":"wait, sorry, it turns out this problem is caused earlier than my last commit","date":"2013-08-18T02:38:14.717Z","type":"message"}
{"nick":"tjfontaine","message":"basically you're passing an empty local around","date":"2013-08-18T02:38:30.533Z","type":"message"}
{"nick":"Domenic_","message":"where?","date":"2013-08-18T02:39:10.518Z","type":"message"}
{"nick":"tjfontaine","message":"the frustrating part of the new abort layout is you don't necessarily get the native stack","date":"2013-08-18T02:39:12.514Z","type":"message"}
{"nick":"tjfontaine","message":"whereas on unicies you'd get a core file and we could get a sane[r] backtrace","date":"2013-08-18T02:39:31.318Z","type":"message"}
{"nick":"tjfontaine","message":"test\\simple\\test-vm-basic.js seems to be the inducer","date":"2013-08-18T02:39:54.981Z","type":"message"}
{"nick":"Domenic_","message":"right yes :P","date":"2013-08-18T02:39:59.614Z","type":"message"}
{"nick":"tjfontaine","message":"specifically runInNewContext","date":"2013-08-18T02:40:15.726Z","type":"message"}
{"nick":"tjfontaine","message":"but the problem is in native land","date":"2013-08-18T02:40:28.673Z","type":"message"}
{"nick":"Domenic_","message":"it turns out if i use process.binding('contextify').runInNewContext instead of vm.runInNewContext to bootstrap the module system, the stack traces are much saner...","date":"2013-08-18T02:40:40.158Z","type":"message"}
{"nick":"Domenic_","message":"but, is there somewhere in there that would help me understand what's wrong with the C++?","date":"2013-08-18T02:41:22.014Z","type":"message"}
{"nick":"tjfontaine","message":"well, if you run it in the vs debugger","date":"2013-08-18T02:41:40.651Z","type":"message"}
{"nick":"Domenic_","message":"oh right of course, thanks","date":"2013-08-18T02:41:47.327Z","type":"message"}
{"nick":"kazupon","reason":"Remote host closed the connection","date":"2013-08-18T02:42:57.262Z","type":"quit"}
{"nick":"Domenic_","message":"tjfontaine: this line is causing the problem: https://github.com/domenic/node/blob/b14d196d046ff49c2b43fad3857227c0a273e805/src/node_contextify.cc#L421 any ideas what i'm doing wrong?","date":"2013-08-18T02:47:22.542Z","type":"message"}
{"nick":"tjfontaine","message":"Domenic_: I would guess ContextFromNewSandbox is somehow returning null?","date":"2013-08-18T02:48:23.254Z","type":"message"}
{"nick":"tjfontaine","message":"er no","date":"2013-08-18T02:48:39.938Z","type":"message"}
{"nick":"tjfontaine","message":"where is context::scope?","date":"2013-08-18T02:49:04.019Z","type":"message"}
{"nick":"tjfontaine","message":"oh I guess that's v8","date":"2013-08-18T02:49:10.089Z","type":"message"}
{"nick":"Domenic_","message":"ya","date":"2013-08-18T02:49:15.806Z","type":"message"}
{"nick":"Domenic_","message":"oh it is returning null i think","date":"2013-08-18T02:49:33.959Z","type":"message"}
{"nick":"tjfontaine","message":"ya, I woudl check if that's returning null","date":"2013-08-18T02:49:35.828Z","type":"message"}
{"nick":"Domenic_","message":"well there's a null somewhere","date":"2013-08-18T02:49:47.576Z","type":"message"}
{"nick":"tjfontaine","message":"which probably means sandbox is null?","date":"2013-08-18T02:49:49.342Z","type":"message"}
{"nick":"Domenic_","message":"when i hover over context in CompileRunInNewContext it's non-null","date":"2013-08-18T02:50:13.837Z","type":"message"}
{"nick":"Domenic_","message":"but when i hover over context in v8::Context::Scope::Scope it's null","date":"2013-08-18T02:50:26.576Z","type":"message"}
{"nick":"Domenic_","message":"think i got it: https://github.com/domenic/node/blob/b14d196d046ff49c2b43fad3857227c0a273e805/src/node_contextify.cc#L502 // 0 should be i","date":"2013-08-18T02:54:29.766Z","type":"message"}
{"nick":"tjfontaine","message":"if you say so, I am not very familiar with the code paths :)","date":"2013-08-18T02:55:25.586Z","type":"message"}
{"nick":"Domenic_","message":"ok well it's still crashing but at tleast this time it's clearly because the returned context is null","date":"2013-08-18T02:55:47.218Z","type":"message"}
{"nick":"Domenic_","message":"is there something bad about the way i'm using PersistentToLocal perhaps?","date":"2013-08-18T02:56:00.450Z","type":"message"}
{"nick":"Domenic_","message":"In ContextFromNewSandbox","date":"2013-08-18T02:56:06.835Z","type":"message"}
{"nick":"tjfontaine","message":"oh","date":"2013-08-18T02:56:49.811Z","type":"message"}
{"nick":"tjfontaine","message":"ya, just return ctx->context_ I think is sufficient","date":"2013-08-18T02:57:46.058Z","type":"message"}
{"nick":"tjfontaine","message":"that persistent is going out of scope, which I think kills the persistent","date":"2013-08-18T02:58:08.862Z","type":"message"}
{"nick":"tjfontaine","message":"I think there's a comment about it","date":"2013-08-18T02:58:17.651Z","type":"message"}
{"nick":"Domenic_","message":"ok cool thanks","date":"2013-08-18T02:58:55.979Z","type":"message"}
{"nick":"tjfontaine","message":"https://github.com/joyent/node/blob/master/src/node_internals.h#L71-L73","date":"2013-08-18T02:59:02.258Z","type":"message"}
{"nick":"tjfontaine","message":"I believe there's an implicit Dispose because the Persistent goes out of scope","date":"2013-08-18T02:59:14.755Z","type":"message"}
{"nick":"tjfontaine","message":"but don't quote me on that","date":"2013-08-18T02:59:34.190Z","type":"message"}
{"nick":"Domenic_","message":"oh, i am forgetting to wrap the context around something","date":"2013-08-18T03:03:15.303Z","type":"message"}
{"nick":"tjfontaine","message":"that also matters","date":"2013-08-18T03:03:27.450Z","type":"message"}
{"nick":"Domenic_","message":"is there any way I can just do `new ContextifyContext()`, but from C++?","date":"2013-08-18T03:15:30.568Z","type":"message"}
{"nick":"Domenic_","message":"doing that gives me so much: it sets up the objectwrap, plugs the sandbox into the internals, etc. but i need a ContextifyContext* instance, in C++... last time I solved this by passing one in from JS, but that won't do here.","date":"2013-08-18T03:16:52.815Z","type":"message"}
{"nick":"tjfontaine","message":"from the template function NewInstance","date":"2013-08-18T03:22:29.605Z","type":"message"}
{"nick":"Domenic_","message":"sweet i think that did the trick. back to comprehensible errors.","date":"2013-08-18T03:35:09.754Z","type":"message"}
{"nick":"Domenic_","message":"is there any way to do that and also pass in an argument?","date":"2013-08-18T03:39:57.863Z","type":"message"}
{"nick":"mikeal","reason":"Ping timeout: 240 seconds","date":"2013-08-18T03:45:02.541Z","type":"quit"}
{"nick":"c4milo","reason":"Remote host closed the connection","date":"2013-08-18T03:50:33.236Z","type":"quit"}
{"nick":"c4milo","date":"2013-08-18T04:11:55.015Z","type":"join"}
{"nick":"mikeal","date":"2013-08-18T04:13:37.334Z","type":"join"}
{"nick":"jmar777","date":"2013-08-18T04:21:27.302Z","type":"join"}
{"nick":"c4milo","reason":"Remote host closed the connection","date":"2013-08-18T04:44:04.159Z","type":"quit"}
{"nick":"jmar777","reason":"Remote host closed the connection","date":"2013-08-18T04:51:22.108Z","type":"quit"}
{"nick":"mikeal","reason":"Read error: Connection reset by peer","date":"2013-08-18T04:59:45.306Z","type":"quit"}
{"nick":"mikeal1","date":"2013-08-18T04:59:51.198Z","type":"join"}
{"nick":"mikeal1","reason":"Client Quit","date":"2013-08-18T05:02:06.322Z","type":"quit"}
{"nick":"mikeal","date":"2013-08-18T05:06:00.756Z","type":"join"}
{"nick":"mjr__","date":"2013-08-18T05:12:14.958Z","type":"join"}
{"nick":"groundwater","date":"2013-08-18T05:49:34.241Z","type":"join"}
{"nick":"groundwater","reason":"Client Quit","date":"2013-08-18T05:52:14.686Z","type":"quit"}
{"nick":"mikeal","reason":"Quit: Leaving.","date":"2013-08-18T05:56:07.796Z","type":"quit"}
{"nick":"groundwater","date":"2013-08-18T06:12:23.343Z","type":"join"}
{"nick":"groundwater","reason":"Client Quit","date":"2013-08-18T06:13:53.414Z","type":"quit"}
{"nick":"mikeal","date":"2013-08-18T06:26:17.548Z","type":"join"}
{"nick":"groundwater","date":"2013-08-18T06:34:06.286Z","type":"join"}
{"nick":"dap","date":"2013-08-18T06:39:48.974Z","type":"join"}
{"nick":"dap","reason":"Client Quit","date":"2013-08-18T06:44:17.306Z","type":"quit"}
{"nick":"dap","date":"2013-08-18T06:50:38.761Z","type":"join"}
{"nick":"dlmanning","reason":"Quit: reboot","date":"2013-08-18T06:51:39.240Z","type":"quit"}
{"nick":"MI6","message":"\u0002nodejs-v0.10-windows\u0002: #154 \u00037UNSTABLE\u000f windows-ia32 (8/597) windows-x64 (8/597) http://jenkins.nodejs.org/job/nodejs-v0.10-windows/154/","date":"2013-08-18T06:52:44.980Z","type":"message"}
{"nick":"stagas","date":"2013-08-18T07:21:45.811Z","type":"join"}
{"nick":"groundwater","reason":"Quit: groundwater","date":"2013-08-18T07:23:47.207Z","type":"quit"}
{"nick":"rendar","date":"2013-08-18T07:24:51.838Z","type":"join"}
{"nick":"dap","reason":"Quit: Leaving.","date":"2013-08-18T07:39:48.927Z","type":"quit"}
